#!/usr/bin/env bash
# Install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Create HTML page with Hello World!
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Redirect
sudo sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/kpwtHgo_Cd4?si=J8jgfzOS-_jGT9PU;\n\t}' /etc/nginx/sites-available/default

# 404 not found page
echo 'Ceci n'est pas une page' | sudo tee /var/www/html/404.html
sudo sed -i '/server_name _;/a \\n\terror_page 404 /404.html;' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
