#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend estebanweb
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 485647-web-01    54.242.96.122:80 check
    server 485647-web-02	 	54.197.45.25:80 check" >>/etc/haproxy/haproxy.cfg

sudo service haproxy restart