#!/usr/bin/env bash
# Install HAProxy
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get update
sudo apt-get -y install haproxy=2.8.\*

# Configure HAproxy so that it send traffic to web-01 and web-02
echo -e "\nbackend web-backend\n\tbalance roundrobin\n\tserver 485647-web-01 54.242.96.122 check\n\tserver 485647-web-02 54.197.45.25 check\n\nfrontend web-frontend\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend" | sudo tee -a /etc/haproxy/haproxy.cfg

# Start haproxy
sudo service haproxy start
