#!/usr/bin/env bash
# This script is displaying "Hi" if i = 9 else display Best School

counter=1

while [ $counter -le 10 ]
do
    if [ $counter -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
((counter++))
done
    